name: Validation CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: [3.0.6, 2.7.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install dependencies
      run: bundle install

    - name: Run Makefile
      if: matrix.os == 'ubuntu-latest'
      run: make spec cli

    - name: Run Windows
      if: matrix.os == 'windows-latest'
      run: |
          bundle exec rspec spec
          cli.ps1
